---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Instala depedências
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - vim
        - htop
        - curl
        - wget
        - ncdu
        - tree
        - apt-transport-https
        - ca-certificates
        - gnupg
        - python3-pip
        - make
        - git
        #- bash-completion
        - gnupg-agent
        - flameshot
        #- fonts-hack
        #- tilix
        - mlocate
        - jq
        - mtr
        - zip
        - unzip
        #- openjdk-11-jdk
        - xrdp
        - ubuntu-desktop

    - name: Install Google Key
      apt_key: 
        url: 'https://dl.google.com/linux/linux_signing_key.pub'
        state: present
    - name: Install Google Repository
      apt_repository:
        repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
        state: present
        filename: google-chrome
    - name: Install Google Chrome
      apt:
        name: google-chrome-stable


    - name: Install Docker Key
      apt_key:
        url: 'https://download.docker.com/linux/ubuntu/gpg'

    - name: Install Docker Repository
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
        state: present
        filename: docker-ce
  
    - name: Install Docker
      apt:
        name: docker-ce
    - name: Adding existing user to group Docker
      become: yes
      user: 
        name: '{{ ansible_user_id }}'
        groups: docker 
        append: yes
    - name: Install Docker-Compose
      get_url:
        url: 'https://github.com/docker/compose/releases/download/1.26.2/docker-compose-Linux-x86_64'
        dest: '/usr/local/bin/docker-compose'
        mode: 755
    
    - name: Add Vagrant permissão para executar o docker
      command: usermod -aG docker vagrant

    - name: Clone de APP de exemplo
      ansible.builtin.git:
        repo: https://github.com/silvemerson/WebDemo.git
        dest: /home/vagrant/WebDemo
        single_branch: yes
        version: master

    - name: Install docker package
      ansible.builtin.pip:
        name: docker

    - name: Install specified python requirements
      ansible.builtin.pip:
        requirements: /home/vagrant/WebDemo/requirements.txt

    - name: Pull robot-framework
      community.docker.docker_image:
        name: ppodgorsek/robot-framework:latest
        source: pull   
    - name: Configurando ABNT2
      commando: apt-get install language-pack-gnome-pt language-pack-pt-base

    - name: Reboot the server
      tags: reboot
      become: yes
      become_user: root
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0